### ISSUE TITLE
selecting item deletes item from list

### ISSUE THREAD

**Issue by vanessascode** [BuddyForms/BuddyForms-Pods#1]
![arco_lis_deleted](https://user-images.githubusercontent.com/18070947/60611070-11dc8800-9dce-11e9-86d2-58c846cfffd6.png)
Team: PostLab
Problem: selecting item from related_team deletes item from list deletes the item in the list
Example: ARCO (LIS) is not in the list anymore after selection
Expected outcome: team selected in the list is highlighted and stays visible and selected in the list
Time/date: 03.07.2019 at 6pm
Web browser: Google Crome Version 72.0.3626.109

**Comment by vanessascode** [comment]
@svenl77 I will try to create a step-by-step guide if I can recreate the bug again

**Comment by vanessascode** [comment]
Here is a screenvideo about adding a new software where from the front end side the items seems to be deleted and from the dasboard the selected items are not saved. The related_team field is different than others due to the amount of the items (for example 40, and we would be have more than 40). When the field changes to autocomplete field, it does not show well. With 30 it works nicely. Perhaps you can help on this @svenl77 ?

[related_team.mov.zip](https://github.com/BuddyForms/BuddyForms-Pods/files/3372431/related_team.mov.zip)

**Comment by svenl77** [comment]
Hi @vanessascode I did not see any issue. Only how you fill out a form and submit it.

Can you send me a clone of your site or export of the pods?

**Comment by vanessascode** [comment]
@svenl77 , thank you for the quick answer, I talked with Driss and we found a temporary solution but it would still be nice if the auto-completion field rendering can be corrected, so if you have 30 items in the list versus 40, you will notice the field changing the way it works. Could you test it with these amount of items? I will ask about export of the pods.

**Comment by vanessascode** [comment]
@svenl77 from Driss: "He can reproduce the bug by changing the value of the variable $limit from 30 to a smaller number of post in 'pods/classes/fields/pick.php' at line 2142.

if ( $autocomplete ) {
                    if ( 0 === $limit ) {
                        $limit = 30;
                    }

He can also look at /pods/ui/admin/form.php to see lines 474 and 498.

**Comment by svenl77** [comment]
@vanessascode should be fixed with the last commit!
