### ISSUE TITLE
How to integrate BuddyForms with Pods

### ISSUE THREAD

**Issue by rhavil** [BuddyForms/BuddyForms-Pods#2]
Hello I'm so glad to see this Git open! I have been looking for a way to relate Buddyforms with Pods. How do I install it? I'm looking to get to be able to post a journal/diary style with hierarchical taxonomies. Thanks.

**Comment by svenl77** [comment]
Just install it and then you have a new form element for Pods Fields and Pods Field Groups. You can also map exiting Buddyforms Fields with Pods. Thre is a new tab for this in the form elements.

Let us know your feedback. I'm keen to get some user feedback about it.
