### ISSUE TITLE
elements goes above 30 an autocomplete mode replaces the dropdow list

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-Pods#3]
Hello, there is an issue on pods related fields. When there elements goes above 30 an autocomplete mode replaces the dropdow list. buddyforms pods doesn't manage that. In the example related team has more than hundred elements. This issue appears when adding 'pods field' one by one on the form. It doesn't appear when we add a whole 'pods fields'.
![Issue_autocomplete](https://user-images.githubusercontent.com/645567/66187205-29046d80-e67c-11e9-98f6-3ae42b53d4ca.png)

**Comment by svenl77** [comment]
This issue shoukld be fixed now with the new whay we load the assets. If not please reopen

**Comment by drisssadoun** [comment]
Hello, the bug is still not fixed.

**Comment by svenl77** [comment]
@marin250189 and @gfirem you implememnted the new validation for the ACF. Can you take a look into pods please if we can addaped the error handling and manage the assets in a better way so that this issue not come up.

**Comment by gfirem** [comment]
the fix of this issue is already deployed in the develop branch
