### ISSUE TITLE
Value of pods slug fields are always defined as 'pods_field_key' 

### ISSUE THREAD

**Issue by drisssadoun** [BuddyForms/BuddyForms-Pods#4]
Hello, 

I needed to use the slug of pods field. Unfortunately, in the code the given slug value was always  defined to the string 'pods_field_key'. See in plugin buddyform-pods, inside includes/  form-elements.php line 77. I have corrected the slug value giving  $pods_field instead of 'pods_field_key'. Could you please take this correction into account in your next update.  

> 77 buddyforms_options[form_fields][" . $field_id . "][slug]", **'pods_field_key'** );
> Replaced by
> 77 buddyforms_options[form_fields][" . $field_id . "][slug]", **'$pods_field** );

![Slug_pods_field_key](https://user-images.githubusercontent.com/46719947/70056139-3cc84380-15db-11ea-9b07-827670705292.png)
![Slug_corrected](https://user-images.githubusercontent.com/46719947/70056149-40f46100-15db-11ea-9930-6ffe348bdfbc.png)
![slug_code_old](https://user-images.githubusercontent.com/46719947/70056285-7bf69480-15db-11ea-85cc-10df7dfb3c93.png)
![code_slug_corrected](https://user-images.githubusercontent.com/46719947/70056293-7ef18500-15db-11ea-9fbe-0558a226e67c.png)

**Comment by svenl77** [comment]
Hi @drisssadoun If you work on the code it would be perfect if you create a pull request and commit your changes. Otherwise there is a great danger that changes will not go into a upcoming verasion and stuck in the issue ticket.
